apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser-amass
  namespace: security-tools
  labels:
    app: parser-amass
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parser-amass
  template:
    metadata:
      labels:
        app: parser-amass
    spec:
      containers:
      - name: parser
        image: securecodebox/parser-amass:latest
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: parser-amass
  namespace: security-tools
  labels:
    app: parser-amass
spec:
  selector:
    app: parser-amass
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP

