apiVersion: v1
kind: ServiceAccount
metadata:
  name: securecodebox-operator
  namespace: security-tools
  labels:
    app: securecodebox-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: securecodebox-operator
  labels:
    app: securecodebox-operator
rules:
- apiGroups: ["execution.securecodebox.io"]
  resources: ["scans", "scantypes", "cascadingrules"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: securecodebox-operator
  labels:
    app: securecodebox-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: securecodebox-operator
subjects:
- kind: ServiceAccount
  name: securecodebox-operator
  namespace: security-tools

