apiVersion: v1
kind: Namespace
metadata:
  name: security-tools
  labels:
    name: security-tools
    purpose: security-scanning-tools
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    purpose: gitops-deployment

