apiVersion: v1
kind: Secret
metadata:
  name: pandora-secrets
  namespace: pandora-box
type: Opaque
data:
  # PostgreSQL 密碼 (base64 encoded)
  postgres-password: cGFuZG9yYTEyMw==  # pandora123
  postgres-user: cGFuZG9yYQ==          # pandora
  
  # Redis 密碼
  redis-password: cGFuZG9yYTEyMw==     # pandora123
  
  # Grafana 密碼
  grafana-password: cGFuZG9yYTEyMw==   # pandora123
  
  # JWT 密鑰
  jwt-secret: cGFuZG9yYS1qd3Qtc2VjcmV0LWtleQ==  # pandora-jwt-secret-key
  
  # mTLS 憑證 (需要實際憑證)
  mtls-cert: ""  # 需要實際的 base64 編碼憑證
  mtls-key: ""   # 需要實際的 base64 編碼私鑰

---
apiVersion: v1
kind: Secret
metadata:
  name: gcr-registry-secret
  namespace: pandora-box
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""  # 需要實際的 docker config JSON
