# Control Service Configuration
# 控制服務配置

service:
  name: control-service
  version: 1.0.0

# gRPC 配置
grpc:
  port: 50053
  max_connections: 100
  connection_timeout: 30s

# HTTP 健康檢查配置
http:
  port: 8083
  read_timeout: 10s
  write_timeout: 10s

# 防火牆配置
firewall:
  backend: iptables  # iptables, nftables, or mock
  default_action: drop
  max_block_duration: 24h
  auto_cleanup: true
  cleanup_interval: 1m

# IP 阻斷配置
ip_blocking:
  enabled: true
  max_blocks: 10000
  default_duration: 1h
  whitelist:
    - 127.0.0.1
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16

# 端口控制配置
port_control:
  enabled: true
  protected_ports:
    - 22    # SSH
    - 3389  # RDP
    - 5432  # PostgreSQL
    - 6379  # Redis

# gRPC 客戶端配置（調用其他服務）
clients:
  device_service:
    url: localhost:50051
    timeout: 10s
    retry_attempts: 3
  network_service:
    url: localhost:50052
    timeout: 10s
    retry_attempts: 3

# RabbitMQ 配置
rabbitmq:
  url: amqp://pandora:pandora123@rabbitmq:5672/
  exchange: pandora.events
  connection_timeout: 30s
  heartbeat_interval: 60s

# 日誌配置
logging:
  level: info
  format: json
  output: stdout

# 監控配置
monitoring:
  enabled: true
  prometheus_port: 9093
  health_check_interval: 30s

